class Entry:
    phonetic: str
    definition: str
    translation: str
    exchanges: list[str]

class Handle:
    name: str
    name_zh: str

    def switch(self): ...
    def __getitem__(self, key: str) -> Entry | None: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: str) -> bool: ...

class Manager:
    def __init__(self): ...
    def create(self, path: str, temp: str, callback: function) -> Handle: ...
    def find(self, target: str) -> str | None: ...
    def filter(self, word: str, seps: list[str]) -> list[str]: ...
    def random(self) -> str | None: ...
    def clear(self): ...
