[workspace]
members = ["entry", "db", "creator", "reader", "serialization", "tests", "interface"]
resolver = "3"

[profile.release]
lto = true
debug = 0
panic = "abort"
opt-level = 3
codegen-units = 1
strip = true
