[package]
name = "creator"
version = "0.1.0"
edition = "2024"

[lib]
name = "creator"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.24"
features = ["extension-module"]

[dependencies.lexi_db]
path = "../lexi_db"

[dependencies.entry]
path = "../entry"
