[package]
name = "entry"
version = "0.1.0"
edition = "2024"

[dependencies.db]
path = "../db"

[dependencies.serialization]
path = "../serialization"

[dependencies.pyo3]
version = "0.*"
features = ["extension-module"]
