from .entry import PyEntry

class PyDBReader:
    def __init__(path: str): ...
    def __getitem__(self, key: str) -> PyEntry | None: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: str) -> bool: ...
    def keys(self) -> list[str]: ...
