[package]
name = "reader"
version = "0.1.0"
edition = "2024"

[lib]
name = "reader"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.24"
features = ["extension-module"]

[dependencies.db]
path = "../db"

[dependencies.entry]
path = "../entry"
