[package]
name = "reader"
version = "0.2.0"
edition = "2024"

[lib]
name = "reader"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.*"
features = ["extension-module"]

[dependencies.db]
path = "../db"

[dependencies.entry]
path = "../entry"

[dependencies.matcher]
path = "../matcher"
